### ISSUE TITLE
Attuned?

### ISSUE THREAD

**Issue by jacobdparker** [axejintao/wizards-viewer#22]
More a question than an issue.  What in your code sets which Affinity a wizard is Attuned to?

**Comment by okjintao** [comment]
hi @jacobdparker 

https://github.com/axejintao/wizards-viewer/blob/8b3e39785f5dace6c2b07d9317c17e29819f790d/src/store/WizardStore.ts#L72-L99

here are where the affinity calculation per wizard is done.

**Comment by jacobdparker** [comment]
Thanks for the response.  From talking with others in the discord it seems the issue with Attunement being misassigned has been taken care of.  Thanks for the response.
